jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/cfs/cdirs/lsst/www/shivamp/GODMAX/run_scripts/perlmutter/sample_params_thetaco.py", line 528, in <module>
    traces = pmap(do_mcmc)(rng_keys)
  File "/global/cfs/cdirs/lsst/www/shivamp/GODMAX/run_scripts/perlmutter/sample_params_thetaco.py", line 487, in do_mcmc
    mcmc.run(
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 675, in run
    states, last_state = partial_map_fn(map_args)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/mcmc.py", line 438, in _single_chain_mcmc
    new_init_state = self.sampler.init(
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 749, in init
    init_params = self._init_state(
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/hmc.py", line 693, in _init_state
    ) = initialize_model(
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/util.py", line 656, in initialize_model
    ) = _get_model_transforms(substituted_model, model_args, model_kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/infer/util.py", line 450, in _get_model_transforms
    model_trace = trace(model).get_trace(*model_args, **model_kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/handlers.py", line 171, in get_trace
    self(*args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  File "/global/cfs/cdirs/lsst/www/shivamp/env/jax_godmax/lib/python3.9/site-packages/numpyro/primitives.py", line 105, in __call__
    return self.fn(*args, **kwargs)
  [Previous line repeated 2 more times]
  File "/global/cfs/cdirs/lsst/www/shivamp/GODMAX/run_scripts/perlmutter/sample_params_thetaco.py", line 393, in model
    prior_min_jp = prior_min_all_dict[sims_params_vary_names[jp]]
KeyError: 'nu_theta_ej_z'
srun: error: nid008421: task 0: Exited with exit code 1
srun: Terminating StepId=27061178.0

real	2m28.838s
user	0m0.046s
sys	0m0.037s
